### PR TITLE
Fse patches

### PR DESCRIPTION
**Pull request by noVaSon**
Hello @ffont !
This is a collection of minor improvements in 2 descriptions and a bunch of maintenance due to depreciation warnings.
I ran the tests successfully and got rid of some warnings.
It should work well!

Best,
Eric

### CODE REVIEW

**Comment by ffont** [comment]
Hi @noVaSon,
Thanks for the PR, it looks good. It looks like this also includes the commits in https://github.com/ffont/freesound-explorer/pull/36, is that right? If that is the case, I'll close the other one and merge this one.

**Comment by noVaSon** [comment]
Hi @ffont!
Sure! This would be grand!
Best,
Eric

**Comment by noVaSon** [comment]
Oh @ffont !
I made a terrible mistake:

commit 1dcf396
was included - but I build all my features before this commit.
This means I would have to edit every single file still containing React.PropTypes again to PropTypes for every branch and every pull request!

My suggestion:
Please revert this pull request and I send it again at the end of all feature PRs.
Alternative:
I make a new Patch-PR without this one commit I messed up to exclude.

Would you please detangle this?
Good to know that it works anyway...

Cheers!

**Comment by noVaSon** [comment]
@ffont -
nevermind.
I decided to do it by hand per PR, it wouldn't be as much work as I expected ^^

**Pull request merged**
