### PR TITLE
Solves stop playing BUG

### PR DESCRIPTION
**Pull request by noVaSon**
The playing source nodes had no unique key in the object.
Used UUID instead, now stop all sounds playing by clicking on the map works like a charm!
This Branch is currently on par with ffont:master,
it needs to be merged again when other PRs are done.

Adresses #42

### CODE REVIEW

**Comment by ffont** [comment]
Hi @noVaSon I just merged the other PRs and deployed. So cool, awesome work!!
To celebrate I made a quick stupid loop (attached here) with the explorer, all worked so nice. Just too bad that the record feature does not automatically [start/end recording in sync with the metronome](https://github.com/ffont/freesound-explorer/issues/35).

Le me know when this PR is ready after the re-merge.

[freesound_explorer_28_8_2018_16_49_9.wav.zip](https://github.com/ffont/freesound-explorer/files/2328568/freesound_explorer_28_8_2018_16_49_9.wav.zip)

**Comment by noVaSon** [comment]
MERGED!

Thanks @ffont ! This means a lot to me :)

I'll have a look at other issues as time goes by / 
Your loop sounds like having accomplished a new highscore to me ^^
Seems like I really got cached by this stuff.

**Comment by noVaSon** [comment]
@ffont Oh, I know I wanted your to freeze the repo until 15th sepember - but would you please merge this before? Didn't notice the bug was still there...

I am glad that everything else works so smooth :D 
My Highlight of the year!

**Comment by ffont** [comment]
Done!

**Pull request merged**
