### PR TITLE
WIP Implements the SoundList

### PR DESCRIPTION
**Pull request by noVaSon**
Adresses #40:

Implements a table that is synchronized with the map view.
All functionality except the SoundInfoModal works also in the SoundList.
Based on React-Table.

Features:
see checkboxes in issue
+ is sortable by click on the headers

Improveable:
- scrollbar styling varies significantly amongst different browsers

Looks like this:

screenshot 2018-04-27 16 02 18

### CODE REVIEW

**Comment by ffont** [comment]
I've been testing this feature and it works really great. These are some suggestions for small improvements (mostly layout):

- The "name" header is slightly lower than the other ones right (see pic)? Can this be fixed?
screen shot 2018-05-02 at 10 46 12
 - The height of the list elements could be set as the same as the list of sounds in the paths section (see pic). Actually you can make sure the design is similar.
 - Having the entire row of the color of the sound maybe is "too much" of color. You could try adding a circle of the corresponding color to the left of the name for example.
 - Also it would be nice that when you select a sound in the map, the list scrolls to where the selected sound is visible.
 - Will this list work well with the multi-select feature?
 - I love that the list changes when you switch spaces, but you might want to add the name of the space at the top of the list so this becomes clearer.
 - Maybe we'll want an option to make the sidebar bigger so the list is more readable. For example, when the sidebar is open you have a "maximise" button next to the arrow to make it even bigger. But this is probably not needed right now.

This is really great work @noVaSon, congrats!

**Comment by noVaSon** [comment]
Thanks for your feedback @ffont, this is like harvesting sweet fruit !

In order:
*The "name" header is slightly lower than the other ones right (see pic)? Can this be fixed?*
-> this is a default style of react-table - it indicates the header that determines the table-sorting.
I should be able to change this somehow.

*The height of the list elements could be set as the same as the list of sounds in the paths section (see pic). Actually you can make sure the design is similar.*
-> Yes, shouldn't be too difficult.

*Having the entire row of the color of the sound maybe is "too much" of color. You could try adding a circle of the corresponding color to the left of the name for example.*
-> I thought of this, too - I will try.

*Also it would be nice that when you select a sound in the map, the list scrolls to where the selected sound is visible.*
-> another one that I would also like to change. I will see too it.

*Will this list work well with the multi-select feature?
*
-> I developed both together, so yes, it should! (I will repair if not ;)

*I love that the list changes when you switch spaces, but you might want to add the name of the space at the top of the list so this becomes clearer.*
-> No problem.

*Maybe we'll want an option to make the sidebar bigger so the list is more readable. For example, when the sidebar is open you have a "maximise" button next to the arrow to make it even bigger. But this is probably not needed right now.
*
-> Oh yes, I tried this, but is was too complex for my short time...

**What about this:**

As it is working, we could merge it into the main repo and open issues about the here supposed improvements, as far as I couldn't get it done on the fly before the merge.

**Comment by noVaSon** [comment]
Ok, I merged master into this branch and checked. No obvious issues by now!
Still have to take care for styling issues.

**Comment by ffont** [comment]
@noVaSon nice! let me know when this is ready to test and deploy and I'll do it.

**Comment by noVaSon** [comment]
Ok Hi @ffont !

I applied some style changes, hope you like the idea with the couloured border, this was much simpler and space effective than introducing a column with circles that stay fixed when scrolling to the right.

screenshot 2018-05-23 12 10 51

The last major improvements remain:
- scroll to hovered sound
- make sidebar resizable

These are quiet complex and I can not care for this right now.
I think it is time to merge :)

**Comment by ffont** [comment]
Merged and deployed!
Although I still kind of dislike the layout for the table header in which the text is positioned lower if the column is "selected". I'd rather prefer the gray line appearing on top of the header cell but the text keeping the same position :)

nice work!

**Pull request merged**
