### PR TITLE
Api sorting

### PR DESCRIPTION
**Pull request by noVaSon**
Adresses issue #53:

Adds a quick possibility of pre-filtering the freesound query result.
It simply uses the Freesound API "sort" parameter.

Looks like this:
screenshot 2018-05-03 14 22 32

### CODE REVIEW

**Comment by noVaSon** [comment]
Ok @ffont ! 
Just merged this into master and pushed!
Ready to add the next feature :)

///

It will be time do conduct a new survey then!
*ok, maybe, I'll try to add batch download a last time before as it would be really useful*

**Comment by ffont** [comment]
Hi, I'm not sure I understand the "Just merged this into master and pushed", this PR does not seem to have been merged, has it?

**Comment by ffont** [comment]
After merging the other PRs there is a conflict now with this one. Can you fix it? Then I'll merge and deploy.

**Comment by noVaSon** [comment]
Done!
Next: clustertags

**Comment by noVaSon** [comment]
Hi, I'm not sure I understand the "Just merged this into master and pushed", this PR does not seem to have been merged, has it?
-> just wanted to say that it is updated and ready for merging :) 
Well Done!

**Pull request merged**
