### PR TITLE
B) Shortcut animation

### PR DESCRIPTION
**Pull request by noVaSon**
Select map or sidebar and press space during t-sne calculation to disable the animation.
This can be a radical speed enhancement when requesting 100+ sounds.

This cares for #62

### CODE REVIEW

**Comment by ffont** [comment]
I've been testing a bit and I encountered some weird behavior. These are some comments:

- When animation is stopped, this should be shown in a message (maybe the map progress message can be updated with something like - "animation disabled")
- When hitting space while loading a map I've seen new queries being triggered automatically. I think there is a bug here...
- This is more related to https://github.com/ffont/freesound-explorer/pull/61, but when the query box is empty we should show no "estimated number of results" message because when "search" is clicked then we replace empty query for one of the default queries. Btw, when this happens we should put the text that was used in the input box, otherwise users don't understand what happened.

**Comment by noVaSon** [comment]
Solved the first two issues, will adress the last one in #61

**Comment by noVaSon** [comment]
I could also add an option in the settings tab, but I didn't want to clutter the interface since it is rather easy to remember. What do you think @ffont ?

**Comment by ffont** [comment]
Hi @noVaSon,
I don't think there is a need to add a new option to the settings tab, just making it clear that when there is no input query a "random" query is chosen. I'd say don't show the estimated number of results when input box has less than 4 chars (for example), and replacing the contents of the input box with the chosen random query if search is clicked and input box is empty.

**Comment by noVaSon** [comment]
Hi Frederic!

I wasn’t able to solve the "hit space bug", so I switched to an arbitrary alternative key (x).
Setting the .focus() to the map or the sidebar did not work, so I choose to take another way to quickfix it.

The bug only appears, when you submit the form by clicking the search button, as the focus remains there no matter what I tried. If you submit with return, nothing happens since we are still inside the input form.
So yes, the Problem is not really solved :-/

Any Ideas? Maybe @giuband  can help...

**Comment by ffont** [comment]
Hi @giuband, any ideas about this? :)

**Comment by noVaSon** [comment]
I solved it!

The batch download PR was merged into this one. 
So please merge the other one first, thanks!

**Pull request merged**
