### PR TITLE
Adds stop all sounds playing

### PR DESCRIPTION
**Pull request by noVaSon**
I encountered this annoying issue #42 when using playOnHover.
Longer Sounds would only be stoppable by clicking one playing sound after the other.

Now it is synchonized with deselectAllSounds when clicking the empty map.

Unfortunately, when exthausively using the playOnHover feature some state changes seem to be so slow, that not all sounds will reliably stop.
But the majority of them will, so this is a small improvement.

### CODE REVIEW

**Comment by ffont** [comment]
I don't seem to be able to get this to work. Should all sounds stop playing when I click in an empty point in the map?

**Comment by noVaSon** [comment]
This is true!
I must have accidentally excluded the MapContainer.jsx from the commit!
Should work now.

**Comment by ffont** [comment]
Yeah now it works, although as you mention in the comment it is still a bit buggy. I'll merge that but I won't close issue https://github.com/ffont/freesound-explorer/issues/42. Will add a comment about the buggy behavior that should be fixed at some point.

**Comment by ffont** [comment]
After merging #39 this branch has now conflicts with master. @noVaSon you should merge master to this branch and resolve the conflicts, then I'll merge.

**Pull request merged**
